In [1]:
import pandas as pd

df = pd.read_csv('regulation.txt', )

In [2]:
df

,0.5434804558753967,0.07436756044626236,0.9274773001670837,0.5347446799278259,1.2311781644821167,0.4545213580131531,-1.6938523054122925,Unnamed: 7
0,1.199211,0.729696,-0.201315,0.153081,-0.782409,0.481816,-1.290872,NaN
1,-0.670957,0.335363,2.022865,1.253884,-1.519141,-0.569556,-1.835266,NaN
2,1.237489,-0.086661,0.633220,0.492913,-0.086333,-0.104890,-0.928308,NaN
3,1.878202,0.187565,-0.466951,-0.997083,0.697554,-0.400812,-1.653024,NaN
4,1.605704,-0.445210,0.591274,0.568265,-0.570720,0.567964,-1.626342,NaN
...,...,...,...,...,...,...,...,...
94,0.456542,-0.288213,1.000421,-1.280063,0.542003,0.203660,-1.538463,NaN
95,-0.792428,1.278361,0.554463,1.209974,0.747989,0.110893,-1.452744,NaN
96,1.202828,-1.376670,-1.485283,0.959212,-0.462815,0.821805,-1.576948,NaN
97,0.752678,-0.353236,-0.577372,1.101944,1.071935,0.697133,-1.788417,NaN
98,-0.007441,0.010218,-1.197006,0.895637,0.250146,1.220286,-1.426692,NaN