In [39]:
from typing import List
import pandas as pd
import numpy as np
df = pd.read_csv('THEO.csv')

def add_columns(df: pd.DataFrame) :
    ids = df['ID'].unique()
    rng = np.random.default_rng(42)

    def get_correlated_value(cor : float, value : float, rng) :
        return cor*value + rng.normal(0, 1, 1)[0] * np.sqrt(1-cor**2)

    subsets : List[pd.DataFrame] = []
    for id in ids :
        mask = df['ID'] == id
        subsets.append(df[mask])

    for i, subset in enumerate(subsets) :
        bwt = subset['BWT'].iloc[0]
        cor_10 = get_correlated_value(0.1, bwt, rng)
        cor_50 = get_correlated_value(0.5, bwt, rng)
        cor_70 = get_correlated_value(0.7, bwt, rng)
        normal_random = rng.normal(0, 1, 1)[0]

        subset.insert(len(subset.columns), 'bwt_cor_0.1', cor_10)
        subset.insert(len(subset.columns), 'bwt_cor_0.5', cor_50)
        subset.insert(len(subset.columns), 'bwt_cor_0.7', cor_70)
        subset.insert(len(subset.columns), 'zero', 0.)

        subset.insert(len(subset.columns), 'normal', normal_random)
    
    return pd.concat(subsets, axis=0, ignore_index=True)

df = add_columns(df)

In [40]:
df

,ID,AMT,TIME,DV,CMT,MDV,RATE,BWT,bwt_cor_0.1,bwt_cor_0.5,bwt_cor_0.7,zero,normal
0,1,4.02,0.00,0.00,1,1,0,79.6,8.263190,38.899347,56.255929,0.0,0.940565
1,1,0.00,0.00,0.74,1,0,0,79.6,8.263190,38.899347,56.255929,0.0,0.940565
2,1,0.00,0.25,2.84,1,0,0,79.6,8.263190,38.899347,56.255929,0.0,0.940565
3,1,0.00,0.57,6.57,1,0,0,79.6,8.263190,38.899347,56.255929,0.0,0.940565
4,1,0.00,1.12,10.50,1,0,0,79.6,8.263190,38.899347,56.255929,0.0,0.940565
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,12,0.00,5.07,8.57,1,0,0,60.5,6.166101,30.439390,42.972325,0.0,0.223596
140,12,0.00,7.07,6.59,1,0,0,60.5,6.166101,30.439390,42.972325,0.0,0.223596
141,12,0.00,9.03,6.11,1,0,0,60.5,6.166101,30.439390,42.972325,0.0,0.223596
142,12,0.00,12.05,4.57,1,0,0,60.5,6.166101,30.439390,42.972325,0.0,0.223596
143,12,0.00,24.15,1.17,1,0,0,60.5,6.166101,30.439390,42.972325,0.0,0.223596